### ISSUE TITLE
No darko commands recognized

### ISSUE THREAD

**Issue by denolfe** [dotnil/darko#12]
I am attempting to serve a site locally using darko for the first time. I've installed darko using npm, and the command `darko --help` returns the correct information. However, any of the other commands such as `serve` or `build` return `darko-serve(1) does not exist, try --help`.

I attempted this in both git bash and from windows command line with same results. Any help is appreciated!

OS: Windows 7

**Comment by denolfe** [comment]
Hmm, well it appears i simply needed to run `darko-serve` instead of `darko serve`. This can probably be closed. However, it is worth noting that in the documentation there is no mention of using the dash.

**Comment by dotnil** [comment]
This might be a bug in `darko` command. We shall leave it open for further investigation.

When executing sub commands like `darko serve`, `darko` will try to find the command `darko-serve` and delegate it. This feature is provided by command.js. I'll fix it as soon as possible.

**Comment by dotnil** [comment]
Fixed and released as darko@0.3.6
